include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    todo: ignore
    invalid_annotation_target: ignore # Required for freezed + json_serializable

linter:
  rules:
    # Performance
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Code Quality
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true          # Use debugPrint instead
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true

    # Widget best practices
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    use_super_parameters: true
